### ISSUE TITLE
ripgrep: invalid url to utf8-ranges

### ISSUE THREAD

**Issue by vthriller** [BurntSushi/blog#16]
If you'll try to follow
```
[`utf8-ranges`](https://burntsushi.net/rustdoc/utf8_ranges/)
```
you'll hit redirect to https://docs.rs/utf8_ranges/ (note the `_`), which is 404.

Doing `s/_/-/` in the URL fixes this, and I almost created pull request with that very fix, but decided to just report this once I realized that I can also just replace both /rustdoc/ URLs in the text with direct links to docs.rs, and I don't really know what's better. (And if docs.rs is preferred, should links include versions from ripgrep's Cargo.toml at the time of writing, or just redirect to latest versions? Gaaah, I thought this was going to be an easy fix!).

**Comment by BurntSushi** [comment]
All set! I just replaced them with docs.rs links.
