### ISSUE TITLE
No RSS/ATOM feed

### ISSUE THREAD

**Issue by kevincox** [BurntSushi/blog#3]
Hello, I am very impressed by the content you put on your blog but was disappointed that there is no feed that I could subscribe to. If you could provide a feed that my robots could monitor it would be greatly appreciated because I am sure to forget to do so manually.

Thanks, Kevin

**Comment by BurntSushi** [comment]
Does this help? http://blog.burntsushi.net/index.xml

FYI, I typically publish around one or two posts per year.

**Comment by kevincox** [comment]
That does. It would be helpful if you linked it from your pages so that browsers and tools could find it automatically. :)

**Comment by BurntSushi** [comment]
Is there a standard way to do so? There's a link to it with an icon at the bottom of every page.

**Comment by kevincox** [comment]
``` html
<link rel="alternate" title="Posts Feed" type="application/atom+xml" href="/index.xml"/>
```

Should do the trick.
