### ISSUE TITLE
<code> tag

### ISSUE THREAD

**Issue by Its-Just-Nans** [BurntSushi/blog#36]
In this article https://blog.burntsushi.net/rust-regex-syntax-extensions/

![image](https://github.com/BurntSushi/blog/assets/56606507/34dd052d-f503-49ce-a7ca-7dee53fd61be)

**Comment by BurntSushi** [comment]
The very top of the blog says: 

> WARNING: 2018-04-12: The code snippets for this post are no longer available. This is just as well anyway, since they all depended on an unstable internal compiler interface, which hasn’t existed for years.
